version: 0.1

phases:
  build:
    commands:
      - echo entering build phase
      - mvn clean package
  post_build:
    commands:
      - echo Build completed Successfully
artifacts:
  files:
    - target/user-service.jar
  discard-paths: yes